name: Build iPhone Internal

on:
  push:
    branches: ['main']
    if: ${{ startsWith(github.commit_message, '[ios-build]') }}

jobs:
  build_ios:
    name: Build signed iPhone app
    type: build
    params:
      platform: ios
      profile: preview
      refresh_ad_hoc_provisioning_profile: true
